name: Check Rules

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  checkRules:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: setup-yq
        uses: chrisdickinson/setup-yq@v1.0.0
        with:
          yq-version: 4.18.1

      # Merge individual rules into spectral.yml
      - name: Merge rules
        run: bash ./util/scripts/mergeRules.sh

      # Check that the commited spectral.yml is up to date
      - name: Check spectral.yml
        run: bash ./util/scripts/mergeRules.sh

      # Check that all api types overwrite all rules of spectral.yml
      - name: Check spectral-*.yml
        run: bash ./util/scripts/mergeRules.sh
