# This workflow is responsible for publishing the openapi and asyncapi rulesets.
# It will build the rulesets as individual js files and add them to the "latest" release in github.
# This way it's possible to consume the rulesets using a URL without the need for npm or unpkg e.g.: https://github.com/SchwarzIT/api-linter-rules/releases/download/latest/openapi.js

name: Update Latest Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build

      - name: Update assets of "latest" release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload latest packages/openapi/dist/openapi.js --clobber
          gh release upload latest packages/asyncapi/dist/asyncapi.js --clobber
