name: Wiki Pipeline

on:
  push:
    branches:
      - "testing" # ToDo: Change to "main" before merge

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  updateWiki:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: wiki
  
      - name: install yq
        uses: mikefarah/yq@v4.18.1

      - name: generate docs
        run: bash ./util/scripts/generateDocs.sh ./rules ./wiki

      - name: go to wiki repo
        run: cd ./wiki

      - name: create branch
        run: git branch test && git checkout test

      - name: set commit user
        run: git config user.email "wiki@pipeline" && git config user.name "Wiki Pipeline"

      - name: stage updates
        run: git add *.md

      - name: commit updates
        run: git commit -m "Generated Wiki"

      - name: push changes
        run: git push