name: Wiki Pipeline

on:
  push:
    branches:
      - "testing" # ToDo: Change to "main" before merge

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  updateWiki:
    runs-on: ubuntu-latest
    env:
      working-directory: ./wiki

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: wiki
  
      - name: install yq
        uses: mikefarah/yq@v4.18.1

      - name: generate docs
        run: bash ./util/scripts/generateDocs.sh ./rules ./wiki

      - name: go to wiki repo
        run: cd ./wiki

      - name: ls
        run: ls -la

      - name: ls (working dir)
        working-directory: ${{env.working-directory}}
        run: ls -la

      - name: create branch
        working-directory: ${{env.working-directory}}
        run: git branch test && git checkout test

      - name: set commit user
        working-directory: ${{env.working-directory}}
        run: git config --global user.email "wiki@pipeline" && git config --global user.name "Wiki Pipeline"

      - name: git status
        working-directory: ${{env.working-directory}}
        run: git status

      - name: stage updates
        working-directory: ${{env.working-directory}}
        run: git add *.md

      - name: git status
        working-directory: ${{env.working-directory}}
        run: git status

      - name: commit updates
        working-directory: ${{env.working-directory}}
        run: git commit -m "Generated Wiki"

      - name: push changes
        working-directory: ${{env.working-directory}}
        run: git push